# Generated by Django 5.2.5 on 2026-04-20 22:47

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('csv', 'CSV Import'), ('api', 'API Fetch')], max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('records_created', models.PositiveIntegerField(default=0)),
                ('records_updated', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Data Run',
                'verbose_name_plural': 'Data Runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'unique_together': {('name', 'latitude', 'longitude')},
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Monitoring Station',
                'verbose_name_plural': 'Monitoring Stations',
                'ordering': ['state', 'city'],
                'unique_together': {('address', 'city', 'state')},
            },
        ),
        migrations.CreateModel(
            name='AirQualityRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('source', models.CharField(choices=[('csv', 'CSV Import'), ('api', 'API Fetch')], default='csv', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('o3_mean', models.FloatField(blank=True, null=True)),
                ('o3_1st_max_value', models.FloatField(blank=True, null=True)),
                ('o3_1st_max_hour', models.IntegerField(blank=True, null=True)),
                ('o3_aqi', models.IntegerField(blank=True, null=True, validators=[core.models.validate_aqi])),
                ('co_mean', models.FloatField(blank=True, null=True)),
                ('co_1st_max_value', models.FloatField(blank=True, null=True)),
                ('co_1st_max_hour', models.IntegerField(blank=True, null=True)),
                ('co_aqi', models.IntegerField(blank=True, null=True, validators=[core.models.validate_aqi])),
                ('so2_mean', models.FloatField(blank=True, null=True)),
                ('so2_1st_max_value', models.FloatField(blank=True, null=True)),
                ('so2_1st_max_hour', models.IntegerField(blank=True, null=True)),
                ('so2_aqi', models.IntegerField(blank=True, null=True, validators=[core.models.validate_aqi])),
                ('no2_mean', models.FloatField(blank=True, null=True)),
                ('no2_1st_max_value', models.FloatField(blank=True, null=True)),
                ('no2_1st_max_hour', models.IntegerField(blank=True, null=True)),
                ('no2_aqi', models.IntegerField(blank=True, null=True, validators=[core.models.validate_aqi])),
                ('data_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='core.datarun')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.location')),
            ],
            options={
                'verbose_name': 'Air Quality Record',
                'verbose_name_plural': 'Air Quality Records',
                'ordering': ['-date'],
                'unique_together': {('location', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('apparent_temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('windspeed', models.FloatField(blank=True, null=True)),
                ('precipitation', models.FloatField(blank=True, null=True)),
                ('cloudcover', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(choices=[('csv', 'CSV Import'), ('api', 'API Fetch')], default='api', max_length=10)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_records', to='core.city')),
            ],
            options={
                'verbose_name': 'Weather Record',
                'verbose_name_plural': 'Weather Records',
                'ordering': ['-date'],
                'unique_together': {('city', 'date', 'time')},
            },
        ),
    ]
